language: rust

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/26c8e6948f86c252b26e
    on_success: change
    on_failure: always
    on_start: never

cache:
    apt: true
    directories:
        - target/debug/deps
        - target/debug/build
